 - name: Project One Playbook
   hosts: elk_servers
   become: true
   tasks:

    # configure ELK VM to use more memory
    - sysctl:
        name: vm.max_map_count
        value: "262144"

    # Updating the system using apt-get update and upgrade
    - name: Update apt-get repo and cache
      apt: update_cache=yes force_apt_get=yes
    - name: Upgrade all apt packages
      apt: upgrade=dist force_apt_get=yes

    # installing docker.io
    - name: Install docker through docker.io
      apt: name=docker.io force_apt_get=yes

    # installing python
    - name: Install the python3-pip package
      apt: name=python3-pip force_apt_get=yes

    # installing the python package manager
    - name: Install pip
      pip:
        name: docker

    # Enable the docker server on boot
    - name: Command to enable the docker service on boot
      systemd:
        name: docker
        state: started

    # Downloading the docker container call sebp/elk:761
    - name: Pulling the docker container from sebp
      docker_container:
        name: project_elk
        image: sebp/elk:761
        state: started
        restart_policy: always
        ports:
                - 5601:5601
                - 9200:9200
                - 5044:5044
        
